INSERT INTO book (title, price, pages, isbn, nuart, note, summary, hook, marketing, cover_filename, release_date)
VALUES ('One Piece Tome 1', 13.0, 192, '978-2-35348-278-8', 'xxx xxx x', 'note',
        'One Piece raconte les aventures d''une bande de pirates, menée par leur capitaine Monkey D. Luffy (qui a pour ambition de devenir le roi des pirates) et lancée à la recherche du trésor, nommé One Piece, du légendaire roi des pirates Gol D. Roger, mort sans avoir révélé l''emplacement de son butin.',
        NULL, NULL,
        '040982c3-c83b-4249-aa82-f5490ba8143f', '2025-11-15'),
       ('One Piece Tome 2', 13.0, 192, '978-2-35348-279-5', 'xxx xxx x', 'note',
        'One Piece raconte les aventures d''une bande de pirates, menée par leur capitaine Monkey D. Luffy (qui a pour ambition de devenir le roi des pirates) et lancée à la recherche du trésor, nommé One Piece, du légendaire roi des pirates Gol D. Roger, mort sans avoir révélé l''emplacement de son butin.',
        NULL, NULL,
        '16f83ae0-d994-4cfe-be4d-0959b2833a30', '2025-12-03'),
       ('One Piece Tome 3', 13.0, 176, '978-2-35348-333-4', 'xxx xxx x', 'note',
        'One Piece raconte les aventures d''une bande de pirates, menée par leur capitaine Monkey D. Luffy (qui a pour ambition de devenir le roi des pirates) et lancée à la recherche du trésor, nommé One Piece, du légendaire roi des pirates Gol D. Roger, mort sans avoir révélé l''emplacement de son butin.',
        NULL, NULL, '93ce1c16-95d5-4478-a5ef-b358b68f7be6', '2025-11-28'),
       ('One Piece Tome 4', 13.0, 160, '978-2-35348-352-5', 'xxx xxx x', 'note',
        'One Piece raconte les aventures d''une bande de pirates, menée par leur capitaine Monkey D. Luffy (qui a pour ambition de devenir le roi des pirates) et lancée à la recherche du trésor, nommé One Piece, du légendaire roi des pirates Gol D. Roger, mort sans avoir révélé l''emplacement de son butin.',
        NULL, NULL, '4dbfbfef-a986-47f0-92fe-428aaf6c655c', '2026-01-10'),
       ('Naruto Tome 1', 13.0, 204, '978-2-35348-164-4', 'xxx xxx x', 'note',
        'Dans l''univers de la série, Naruto est un jeune ninja du village de Konoha. Hôte du démon renard à neuf queues, une créature qui a attaqué le village par le passé, il est rejeté par les autres villageois. Son ambition est de devenir Hokage, le chef du village, afin de gagner le respect des habitants.',
        NULL, NULL, 'a8029fb1-33d5-4d4d-ac1d-ab5e55eb7d0d', '2025-11-22'),
       ('Naruto Tome 2', 13.0, 186, '978-2-35348-187-3', 'xxx xxx x', 'note',
        'Dans l''univers de la série, Naruto est un jeune ninja du village de Konoha. Hôte du démon renard à neuf queues, une créature qui a attaqué le village par le passé, il est rejeté par les autres villageois. Son ambition est de devenir Hokage, le chef du village, afin de gagner le respect des habitants.',
        NULL, NULL, '0000fc75-1916-4094-9353-6319b7a12aa4', '2026-02-14'),
       ('Naruto Tome 3', 13.0, 186, '978-2-35348-194-1', 'xxx xxx x', 'note',
        'Dans l''univers de la série, Naruto est un jeune ninja du village de Konoha. Hôte du démon renard à neuf queues, une créature qui a attaqué le village par le passé, il est rejeté par les autres villageois. Son ambition est de devenir Hokage, le chef du village, afin de gagner le respect des habitants.',
        NULL, NULL, '6573832a-e877-4b23-86ec-9f8d6da70698', '2025-12-18'),
       ('Naruto Tome 4', 13.0, 192, '978-2-35348-215-3', 'xxx xxx x', 'note',
        'Dans l''univers de la série, Naruto est un jeune ninja du village de Konoha. Hôte du démon renard à neuf queues, une créature qui a attaqué le village par le passé, il est rejeté par les autres villageois. Son ambition est de devenir Hokage, le chef du village, afin de gagner le respect des habitants.',
        NULL, NULL, '583efe5d-e478-4c2b-bbce-e082f4fb26d9', '2026-01-25'),
       ('Bleach Tome 1', 13.0, 180, '978-2-35348-179-8', 'xxx xxx x', 'note',
        'Adolescent de quinze ans, Ichigo Kurosaki possède un don particulier : celui de voir les esprits. Un jour, il croise la route d''une belle Shinigami (un être spirituel) en train de pourchasser une "âme perdue", un esprit maléfique qui hante notre monde et n''arrive pas à trouver le repos.',
        NULL, NULL, '29a8425f-c628-42e9-8c28-53deaeec56dc', '2025-11-08'),
       ('Shinjuku Fever Tome 1', 8.5, 224, '978-2-35348-369-3', 'xxx xxx x', 'note',
        'Fuku est le dernier supporter de son lycée de province. Un garçon maladroit mais idéaliste, qui exerce sa fonction avec une énergie folle, même quand son équipe de base-ball subit une raclée ! Monté à Tokyo pour des cours de soutien, Fuku ne va pas tarder à être distrait de ses études au contact de jolies filles très sociables, qui vont l''entraîner dans un monde inconnu : la vie nocturne de Shinjuku !',
        NULL, NULL, '55751857-97a8-4805-97da-95bd2c900f79', '2026-02-28'),
       ('Berserk Tome 1', 60.0, 896, '978-2-35348-342-6', 'xxx xxx x', 'note',
        'Véritable fresque médiévale et épique dark fantasy, Berserk raconte l''histoire de Guts, un guerrier solitaire décidé à être seul maître de son destin, maudit par une mystérieuse marque démoniaque qui, à la nuit tombée, attire des démons sortis tout droit des pires enfers.',
        NULL, NULL, 'c359d90e-e18b-48f6-98db-ac610c2a2934', '2025-12-12'),
       ('Fragment of Horror', 18.0, 192, '978-2-35348-205-4', 'xxx xxx x', 'note',
        'Un homme volage prisonnier de son futon, une maison classée au patrimoine national dont l''antique charpente semble habitée par un esprit lascif, un cheveu de sorcière tranchant comme une guillotine ensanglantée ou encore une femme obsédée depuis l''enfance par les scalpels et les éviscérations...',
        NULL, NULL, 'c6c4868b-606c-4164-9a33-36dc008655cb', '2026-01-17'),
       ('One Piece Tome 5', 13.0, 176, '978-2-35348-357-0', 'xxx xxx x', 'note',
        'One Piece raconte les aventures d''une bande de pirates, menée par leur capitaine Monkey D. Luffy (qui a pour ambition de devenir le roi des pirates) et lancée à la recherche du trésor, nommé One Piece, du légendaire roi des pirates Gol D. Roger, mort sans avoir révélé l''emplacement de son butin.',
        NULL, NULL, '2ac93b25-bde8-48d7-9dbd-eb3a549db858', '2026-02-05'),
       ('One Piece Tome 6', 13.0, 158, '978-2-35348-366-2', 'xxx xxx x', 'note',
        'One Piece raconte les aventures d''une bande de pirates, menée par leur capitaine Monkey D. Luffy (qui a pour ambition de devenir le roi des pirates) et lancée à la recherche du trésor, nommé One Piece, du légendaire roi des pirates Gol D. Roger, mort sans avoir révélé l''emplacement de son butin.',
        NULL, NULL, 'a743cdd5-4bda-4c82-bb69-d81e49d6541f', '2025-11-30'),
       ('Bakuman Vol.1', 12.0, 176, '978-2-35348-280-1', 'xxx xxx x', 'note',
        'Moritaka Mashiro, surnommé Saïko par ses amis, est en 3e année de collège et ses dons pour le dessin lui ont permis de remporter plusieurs prix. Il est amoureux en secret de Miho Azuki mais n''ose pas lui révéler cet amour jusqu''à ce que son ami, Akito Takagi, force le destin.',
        NULL, NULL, '87c58f6b-5364-4066-83d8-1570ef6c2b50', '2026-01-05'),
       ('Bakuman Vol.2', 12.0, 168, '978-2-35348-281-8', 'xxx xxx x', 'note',
        'Moritaka Mashiro, surnommé Saïko par ses amis, est en 3e année de collège et ses dons pour le dessin lui ont permis de remporter plusieurs prix. Il est amoureux en secret de Miho Azuki mais n''ose pas lui révéler cet amour jusqu''à ce que son ami, Akito Takagi, force le destin.',
        NULL, NULL, '357dca81-3c93-4473-ab84-7d5640cae411', '2025-12-20'),
       ('Bakuman Vol.3', 12.0, 184, '978-2-35348-334-1', 'xxx xxx x', 'note',
        'Moritaka Mashiro, surnommé Saïko par ses amis, est en 3e année de collège et ses dons pour le dessin lui ont permis de remporter plusieurs prix. Il est amoureux en secret de Miho Azuki mais n''ose pas lui révéler cet amour jusqu''à ce que son ami, Akito Takagi, force le destin.',
        NULL, NULL, '9a17dbec-f429-42da-b4de-b910b3c3357e', '2026-02-22');

INSERT into author(name)
VALUES ('Eiichiro Oda'),
       ('Makashi Kishimoto'),
       ('Kentarō Miura'),
       ('Junji Ito'),
       ('Tsugumi Ōba'),
       ('Kubo Mitsuro'),
       ('Tite Kubo');


INSERT INTO book_author (book_id, author_id)
VALUES ((SELECT id FROM book WHERE id = 1), (SELECT id FROM author WHERE id = 1)),
       ((SELECT id FROM book WHERE id = 2), (SELECT id FROM author WHERE id = 1)),
       ((SELECT id FROM book WHERE id = 3), (SELECT id FROM author WHERE id = 1)),
       ((SELECT id FROM book WHERE id = 4), (SELECT id FROM author WHERE id = 1)),
       ((SELECT id FROM book WHERE id = 5), (SELECT id FROM author WHERE id = 2)),
       ((SELECT id FROM book WHERE id = 6), (SELECT id FROM author WHERE id = 2)),
       ((SELECT id FROM book WHERE id = 7), (SELECT id FROM author WHERE id = 2)),
       ((SELECT id FROM book WHERE id = 8), (SELECT id FROM author WHERE id = 2)),
       ((SELECT id FROM book WHERE id = 9), (SELECT id FROM author WHERE id = 7)),
       ((SELECT id FROM book WHERE id = 10), (SELECT id FROM author WHERE id = 6)),
       ((SELECT id FROM book WHERE id = 11), (SELECT id FROM author WHERE id = 3)),
       ((SELECT id FROM book WHERE id = 12), (SELECT id FROM author WHERE id = 4)),
       ((SELECT id FROM book WHERE id = 13), (SELECT id FROM author WHERE id = 1)),
       ((SELECT id FROM book WHERE id = 14), (SELECT id FROM author WHERE id = 1)),
       ((SELECT id FROM book WHERE id = 15), (SELECT id FROM author WHERE id = 5)),
       ((SELECT id FROM book WHERE id = 16), (SELECT id FROM author WHERE id = 5)),
       ((SELECT id FROM book WHERE id = 17), (SELECT id FROM author WHERE id = 5));


